<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Magic extends Model
{
    //
    //构造函数  实例化时被调用
    function __construct($a)
    {
        dump($a);
//        parent::__construct($a);
    }
    //
    function __call($method, $parameters)
    {
        dump('__call');
        return parent::__call($method, $parameters); // TODO: Change the autogenerated stub
    }
    function __toString()
    {
        dump('__toString');
        return parent::__toString(); // TODO: Change the autogenerated stub
    }
    function __clone()
    {
        dump('Magic的克隆方法');
        // TODO: Implement __clone() method.
    }

    function Magic(){
        dump('Magic_function');
        return 'Magic_function';
    }
}
